-- Agentic Learning OS: Feature 2E-1 Agent Run Persistence Foundation
-- Schema for auditable, deterministic, user-isolated Learning Orchestrator runs.

CREATE TABLE IF NOT EXISTS public.agent_runs (
  id TEXT PRIMARY KEY, -- Run ID generated by agent (e.g. run_1789499187132_xyz or UUID)
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  
  -- Trigger & Goal Context
  trigger_type TEXT NOT NULL CHECK (trigger_type IN ('STUDENT_GOAL', 'SYSTEM_EVENT')),
  event_trigger TEXT NOT NULL CHECK (event_trigger IN (
    'MANUAL_GOAL', 'SCHEDULED_AUDIT', 'STUDENT_MISTAKE_LOGGED', 
    'STUDY_SESSION_COMPLETED', 'EXTERNAL_SYNC', 'SKILL_GAP_DETECTED', 
    'PROACTIVE_RECOMMENDATION'
  )),
  goal TEXT NOT NULL,
  trigger_context JSONB DEFAULT '{}'::jsonb,
  
  -- State Machine Status & Canonical State
  current_state TEXT NOT NULL CHECK (current_state IN (
    'IDLE', 'GOAL_RECEIVED', 'OBSERVING', 'CORROBORATING', 'ASSESSING',
    'PLANNING', 'TOOL_SELECTION', 'EXECUTING', 'VERIFYING', 'UPDATING',
    'REPLANNING', 'COMPLETED', 'FAILED', 'WAITING_FOR_APPROVAL'
  )),
  status TEXT NOT NULL DEFAULT 'RUNNING' CHECK (status IN (
    'RUNNING', 'PAUSED_FOR_APPROVAL', 'COMPLETED', 'FAILED', 'CANCELLED'
  )),
  
  -- Execution Safety Counters
  tool_iterations INTEGER NOT NULL DEFAULT 0,
  replans_count INTEGER NOT NULL DEFAULT 0,
  executed_actions_count INTEGER NOT NULL DEFAULT 0,
  
  -- Failure & Approval Context (Auditable)
  failure_info JSONB,
  approval_request JSONB,
  
  -- Working Memory & Transition Audit History (Strictly sanitized, no secrets)
  working_memory JSONB DEFAULT '{}'::jsonb,
  transition_history JSONB NOT NULL DEFAULT '[]'::jsonb,
  
  -- Timestamps
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.agent_runs ENABLE ROW LEVEL SECURITY;

-- Clean existing policies safely before recreating
DROP POLICY IF EXISTS "Users can only view their own agent runs" ON public.agent_runs;
DROP POLICY IF EXISTS "Users can insert their own agent runs" ON public.agent_runs;
DROP POLICY IF EXISTS "Users can update their own agent runs" ON public.agent_runs;
DROP POLICY IF EXISTS "Users can delete their own agent runs" ON public.agent_runs;

-- Strict User-Isolation RLS Policies
CREATE POLICY "Users can only view their own agent runs"
  ON public.agent_runs
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own agent runs"
  ON public.agent_runs
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own agent runs"
  ON public.agent_runs
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own agent runs"
  ON public.agent_runs
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Performance & Observability Indexes
CREATE INDEX IF NOT EXISTS idx_agent_runs_user_id ON public.agent_runs(user_id);
CREATE INDEX IF NOT EXISTS idx_agent_runs_user_status ON public.agent_runs(user_id, status);
CREATE INDEX IF NOT EXISTS idx_agent_runs_user_state ON public.agent_runs(user_id, current_state);
CREATE INDEX IF NOT EXISTS idx_agent_runs_user_updated ON public.agent_runs(user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_runs_completed ON public.agent_runs(user_id, completed_at DESC);
