'use client';

import React, { useState, useEffect, useTransition, useRef } from 'react';
import Link from 'next/link';
import { 
  Sparkles, 
  Brain, 
  Target, 
  CheckCircle2, 
  AlertTriangle, 
  Clock, 
  ShieldCheck, 
  ArrowRight, 
  HelpCircle, 
  RefreshCw, 
  Layers, 
  ListChecks, 
  Check, 
  X,
  Compass,
  Zap,
  Info,
  ChevronDown,
  ChevronUp,
  Award,
  BookOpen,
  Activity,
  Code2,
  Calendar,
  ChevronRight,
  ArrowUpRight,
  Play,
  RotateCcw,
  Edit2,
  BookMarked,
  Plus,
  Minus,
  FlaskConical,
  ArrowLeft,
  Milestone
} from 'lucide-react';
import { GlassCard } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  runStudentGoalOrchestrator, 
  approveAndExecuteOrchestratorTask, 
  completeStudentLearningStep,
  resumeStudentLearningJourney,
  OrchestratorRunResult,
  StepExecutionFeedbackResult
} from '@/app/actions/agent-actions';
import { saveRoadmapAsLearningPath } from '@/app/actions/learning-path-actions';
import { useRouter } from 'next/navigation';

const STORAGE_KEY = 'plos_active_learning_coach_run';

const CURATED_GOALS = [
  { 
    label: '2-Day Coding Basics', 
    text: 'I need to learn coding basics in 2 days according to my level.',
    category: 'Foundations'
  },
  { 
    label: '7-Day SQL Optimization', 
    text: 'Master SQL join algorithms, indexing strategies, and query optimization in 7 days.',
    category: 'Database'
  },
  { 
    label: 'Algorithm Patterns', 
    text: 'Solve medium binary tree and dynamic programming problems on LeetCode in 5 days.',
    category: 'Algorithms'
  },
  { 
    label: 'Mistake Remediation', 
    text: 'Review and remediate my recent persistent errors from the mistake log.',
    category: 'Review'
  },
];

type OrchestrationStage = 
  | 'STAGE_1_UNDERSTANDING'
  | 'STAGE_2_ASSESSING'
  | 'STAGE_3_DESIGNING'
  | 'STAGE_4_PREPARING'
  | 'STAGE_READY';

// ============================================================================
// Day-by-Day Roadmap: Inline edit state type
// ============================================================================
type DayPriority = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
interface DayEditState {
  /** Student-edited minutes (undefined means use AI estimate) */
  editedMinutes?: number;
  /** Student-edited priority (undefined means use AI priority) */
  editedPriority?: DayPriority;
  /** Whether the student has made any edit */
  isEdited: boolean;
}

/** Check if all steps in the plan were generated by the day-by-day engine */
function isDayByDayPlan(steps: any[]): boolean {
  return steps.length > 0 && steps.every((s) => s.metadata?.isDayByDay === true);
}

const PRIORITY_CYCLE: DayPriority[] = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'];
const PRIORITY_COLORS: Record<DayPriority, string> = {
  LOW: 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-400 border-emerald-500/30',
  MEDIUM: 'bg-sky-500/15 text-sky-700 dark:text-sky-400 border-sky-500/30',
  HIGH: 'bg-amber-500/15 text-amber-700 dark:text-amber-400 border-amber-500/30',
  URGENT: 'bg-rose-500/15 text-rose-700 dark:text-rose-400 border-rose-500/30',
};

export function LearningCoachView() {
  const [goalText, setGoalText] = useState('');
  const [isPending, startTransition] = useTransition();
  const [runResult, setRunResult] = useState<OrchestratorRunResult | null>(null);
  const [currentStage, setCurrentStage] = useState<OrchestrationStage>('STAGE_READY');
  const [approvalStatus, setApprovalStatus] = useState<'IDLE' | 'APPROVING' | 'APPROVED' | 'REJECTED' | 'FAILED'>('IDLE');
  const [createdTaskInfo, setCreatedTaskInfo] = useState<{ id: string; title: string } | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [completingStepId, setCompletingStepId] = useState<string | null>(null);
  const [stepFeedbackMap, setStepFeedbackMap] = useState<Record<string, StepExecutionFeedbackResult>>({});
  const [stepNotesMap, setStepNotesMap] = useState<Record<string, string>>({});
  const [activeStepId, setActiveStepId] = useState<string | null>(null);
  const [selectedClarifications, setSelectedClarifications] = useState<Record<number, string>>({});
  const [showTechnicalDetails, setShowTechnicalDetails] = useState(false);
  const [resumeNotice, setResumeNotice] = useState<string | null>(null);
  // Day-by-day roadmap inline edits (keyed by stepId)
  const [dayEdits, setDayEdits] = useState<Record<string, DayEditState>>({});
  const [isSavingPath, setIsSavingPath] = useState(false);
  const [savePathResult, setSavePathResult] = useState<{ success: boolean; pathId?: string; error?: string } | null>(null);
  const router = useRouter();

  // 1. Authoritative Persistence: Hydrate server run first, falling back to local cache
  useEffect(() => {
    // Instant local cache restore
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed.runResult) {
          setRunResult(parsed.runResult);
          if (parsed.runResult.learningPlan?.steps?.length > 0) {
            const firstPending = parsed.runResult.learningPlan.steps.find((s: any) => s.status !== 'COMPLETED');
            setActiveStepId(firstPending ? firstPending.id : parsed.runResult.learningPlan.steps[0].id);
          }
        }
        if (parsed.goalText) setGoalText(parsed.goalText);
        if (parsed.approvalStatus) setApprovalStatus(parsed.approvalStatus);
        if (parsed.createdTaskInfo) setCreatedTaskInfo(parsed.createdTaskInfo);
        if (parsed.stepFeedbackMap) setStepFeedbackMap(parsed.stepFeedbackMap);
        if (parsed.stepNotesMap) setStepNotesMap(parsed.stepNotesMap);
      }
    } catch (e) {
      console.warn('Local cache hydration warning:', e);
    }

    // Authoritative server check
    resumeStudentLearningJourney()
      .then((res) => {
        if (res.success && res.context && res.context.learningPlan) {
          const ctx = res.context;
          const serverRunResult: OrchestratorRunResult = {
            success: true,
            runId: ctx.runId,
            status: ctx.pendingStepIds.length === 0 ? 'COMPLETED' : 'COMPLETED',
            goalUnderstanding: ctx.goalUnderstanding || undefined,
            studentAssessment: ctx.studentAssessment || undefined,
            learningDecision: ctx.previousDecision || undefined,
            learningPlan: ctx.learningPlan || undefined,
            adaptivePolicy: ctx.adaptivePolicy || undefined,
          };
          setRunResult(serverRunResult);
          if (ctx.originalGoal) setGoalText(ctx.originalGoal);
          if (ctx.learningPlan?.steps && ctx.learningPlan.steps.length > 0) {
            const firstPending = ctx.learningPlan.steps.find((s) => s.status !== 'COMPLETED');
            setActiveStepId(firstPending ? firstPending.id : ctx.learningPlan.steps[0].id);
          }
        }
      })
      .catch(() => {
        // Offline / dev fallback
      });
  }, []);

  // 2. Cache updates to localStorage
  useEffect(() => {
    if (runResult || goalText || Object.keys(stepFeedbackMap).length > 0) {
      try {
        localStorage.setItem(
          STORAGE_KEY,
          JSON.stringify({
            runResult,
            goalText,
            approvalStatus,
            createdTaskInfo,
            stepFeedbackMap,
            stepNotesMap,
            savedAt: new Date().toISOString(),
          })
        );
      } catch (e) {
        console.warn('Storage sync error:', e);
      }
    }
  }, [runResult, goalText, approvalStatus, createdTaskInfo, stepFeedbackMap, stepNotesMap]);

  // Handle Sequential Real-Time Orchestration Execution
  const handleSubmitGoal = (textToSubmit?: string) => {
    const targetText = textToSubmit || goalText;
    if (!targetText.trim() || isPending) return;

    setErrorMessage(null);
    setRunResult(null);
    setApprovalStatus('IDLE');
    setCreatedTaskInfo(null);
    setStepFeedbackMap({});
    setStepNotesMap({});
    setResumeNotice(null);

    // Progressive stage transitions
    setCurrentStage('STAGE_1_UNDERSTANDING');

    startTransition(async () => {
      // Stage 1 -> Stage 2 transition
      const timer1 = setTimeout(() => {
        setCurrentStage('STAGE_2_ASSESSING');
      }, 600);

      // Stage 2 -> Stage 3 transition
      const timer2 = setTimeout(() => {
        setCurrentStage('STAGE_3_DESIGNING');
      }, 1400);

      // Stage 3 -> Stage 4 transition
      const timer3 = setTimeout(() => {
        setCurrentStage('STAGE_4_PREPARING');
      }, 2200);

      try {
        const result = await runStudentGoalOrchestrator(targetText);
        clearTimeout(timer1);
        clearTimeout(timer2);
        clearTimeout(timer3);
        
        setCurrentStage('STAGE_READY');
        setRunResult(result);
        
        if (result.learningPlan?.steps && result.learningPlan.steps.length > 0) {
          setActiveStepId(result.learningPlan.steps[0].id);
        }

        if (!result.success) {
          setErrorMessage(result.error || 'Unable to complete roadmap. Please try again.');
        }
      } catch (err: any) {
        clearTimeout(timer1);
        clearTimeout(timer2);
        clearTimeout(timer3);
        setCurrentStage('STAGE_READY');
        setErrorMessage(err.message || 'Failed to communicate with Learning Coach.');
      }
    });
  };

  const handleResumeJourney = () => {
    if (isPending) return;

    setErrorMessage(null);
    setResumeNotice(null);

    startTransition(async () => {
      try {
        const res = await resumeStudentLearningJourney();
        if (res.success && res.context && res.context.learningPlan) {
          const ctx = res.context;
          setRunResult({
            success: true,
            runId: ctx.runId,
            status: ctx.pendingStepIds.length === 0 ? 'COMPLETED' : 'COMPLETED',
            goalUnderstanding: ctx.goalUnderstanding || undefined,
            studentAssessment: ctx.studentAssessment || undefined,
            learningDecision: ctx.previousDecision || undefined,
            learningPlan: ctx.learningPlan || undefined,
            adaptivePolicy: ctx.adaptivePolicy || undefined,
          });
          setGoalText(ctx.originalGoal);
          setResumeNotice(res.continuityRationale);
          if (ctx.learningPlan?.steps && ctx.learningPlan.steps.length > 0) {
            const firstPending = ctx.learningPlan.steps.find((s) => s.status !== 'COMPLETED');
            setActiveStepId(firstPending ? firstPending.id : ctx.learningPlan.steps[0].id);
          }
        } else {
          setResumeNotice(res.continuityRationale || 'No active learning journey to resume.');
        }
      } catch (err: any) {
        setErrorMessage(err.message || 'Failed to resume previous journey.');
      }
    });
  };

  const handleCompleteStep = (stepId: string) => {
    if (!runResult?.learningPlan || completingStepId) return;

    setCompletingStepId(stepId);
    setErrorMessage(null);

    startTransition(async () => {
      try {
        const studentNotes = stepNotesMap[stepId] || '';
        const res = await completeStudentLearningStep({
          plan: runResult.learningPlan!,
          stepId,
          taskId: createdTaskInfo?.id || null,
          studentNotes,
          selfReportedEvidence: studentNotes ? `Completed work: ${studentNotes}` : undefined,
          verificationOutcome: 'VERIFIED',
        });

        if (res.success) {
          setStepFeedbackMap((prev) => ({ ...prev, [stepId]: res }));
          if (runResult.learningPlan) {
            const updatedSteps = runResult.learningPlan.steps.map((s) =>
              s.id === stepId ? { ...s, status: 'COMPLETED' as const } : s
            );
            setRunResult({
              ...runResult,
              learningPlan: {
                ...runResult.learningPlan,
                steps: updatedSteps,
              },
            });

            // Automatically advance active step
            const nextPending = updatedSteps.find((s) => s.status !== 'COMPLETED');
            if (nextPending) {
              setActiveStepId(nextPending.id);
            }
          }
        } else {
          setErrorMessage(res.error || 'Failed to record step completion.');
        }
      } catch (err: any) {
        setErrorMessage(err.message || 'Error recording step completion.');
      } finally {
        setCompletingStepId(null);
      }
    });
  };

  const handleApproveTask = (decision: 'APPROVED' | 'REJECTED') => {
    if (!runResult?.approvalProposal || approvalStatus === 'APPROVING') return;

    setApprovalStatus('APPROVING');
    startTransition(async () => {
      try {
        const res = await approveAndExecuteOrchestratorTask(runResult.approvalProposal!, decision);
        if (res.success && res.status === 'EXECUTED') {
          setApprovalStatus('APPROVED');
          setCreatedTaskInfo({
            id: res.createdTaskId || 'task-created',
            title: runResult.approvalProposal!.input.title,
          });
        } else if (res.status === 'REJECTED') {
          setApprovalStatus('REJECTED');
        } else {
          setApprovalStatus('FAILED');
          setErrorMessage(res.error || 'Failed to add task.');
        }
      } catch (err: any) {
        setApprovalStatus('FAILED');
        setErrorMessage(err.message || 'Error approving task.');
      }
    });
  };

  const handleSaveToLearningPath = async () => {
    if (!runResult?.learningPlan?.steps || runResult.learningPlan.steps.length === 0) return;
    setIsSavingPath(true);
    setSavePathResult(null);

    try {
      const planSteps = runResult.learningPlan.steps;
      const formattedDays = planSteps.map((step, sIdx) => {
        const meta = (step.metadata as Record<string, any>) || {};
        const dayNum = (meta?.dayNumber as number) ?? sIdx + 1;
        const topic = (meta?.topic as string) ?? step.title;
        const learnContent = (meta?.learnContent as string) ?? step.description;
        const practiceProblems = (meta?.practiceProblems as number) ?? 2;
        const reviewActivity = (meta?.reviewActivity as string) ?? 'Review key takeaways & verify code';
        const evidenceRationale = (meta?.evidenceRationale as string) ?? step.rationale;
        const aiMinutes = (meta?.aiEstimatedMinutes as number) ?? (step.estimatedEffort?.estimatedMinutes ?? 45);
        const aiPriority = (step.priority as DayPriority) || 'MEDIUM';

        const edit = dayEdits[step.id] ?? { isEdited: false };
        const displayMinutes = edit.editedMinutes ?? aiMinutes;
        const displayPriority = (edit.editedPriority ?? aiPriority) as any;

        return {
          dayNumber: dayNum,
          topic,
          learnContent,
          practiceProblems,
          reviewActivity,
          aiEstimatedMinutes: displayMinutes,
          priority: displayPriority,
          evidenceRationale,
        };
      });

      const res = await saveRoadmapAsLearningPath({
        goal: runResult.learningPlan.goal || goalText || 'Personal Learning Goal',
        days: formattedDays,
        planMetadata: {
          planId: runResult.learningPlan.planId,
          priority: runResult.learningPlan.priority,
          totalMinutes: totalDurationMins,
          source: 'LearningCoach',
        },
      });

      setSavePathResult(res);
    } catch (err: any) {
      setSavePathResult({ success: false, error: err.message || 'Failed to save learning path' });
    } finally {
      setIsSavingPath(false);
    }
  };


  const handleReset = () => {
    setGoalText('');
    setRunResult(null);
    setCurrentStage('STAGE_READY');
    setApprovalStatus('IDLE');
    setCreatedTaskInfo(null);
    setErrorMessage(null);
    setStepFeedbackMap({});
    setStepNotesMap({});
    setActiveStepId(null);
    setResumeNotice(null);
    try {
      localStorage.removeItem(STORAGE_KEY);
    } catch (e) {
      console.warn('Storage reset warning:', e);
    }
  };

  // Group steps into Days / Milestones if timeframe is present
  const steps = runResult?.learningPlan?.steps || [];
  const completedStepsCount = steps.filter((s) => s.status === 'COMPLETED').length;
  const progressPercent = steps.length > 0 ? Math.round((completedStepsCount / steps.length) * 100) : 0;
  const totalDurationMins = steps.reduce((acc, s) => acc + (s.estimatedEffort?.estimatedMinutes || 45), 0);
  const formattedHours = Math.floor(totalDurationMins / 60);
  const formattedMins = totalDurationMins % 60;
  const durationLabel = formattedHours > 0 
    ? `~ ${formattedHours}h ${formattedMins > 0 ? `${formattedMins}m` : ''}`
    : `~ ${totalDurationMins}m`;

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-12 font-sans">
      
      {/* 1. Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-[var(--exec-border)]">
        <div className="space-y-1">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-sky-500/10 border border-sky-500/20 text-sky-600 dark:text-sky-400">
              <Brain className="w-5 h-5" />
            </div>
            <div>
              <h1 className="text-xl font-heading font-bold text-[var(--exec-text)] tracking-tight">
                Personal Learning Coach
              </h1>
              <p className="text-xs text-[var(--exec-text-muted)] font-sans">
                Evidence-grounded learning roadmaps tailored to your actual background and timeline.
              </p>
            </div>
          </div>
        </div>

        {runResult && (
          <div className="flex items-center gap-2 shrink-0">
            <Button variant="ghost" size="sm" onClick={handleReset} className="text-xs font-sans">
              <RotateCcw className="w-3.5 h-3.5 mr-1.5" />
              New Goal
            </Button>
          </div>
        )}
      </div>

      {/* 2. Goal Input Section (Only visible when no plan is active or when starting a new goal) */}
      {!runResult && !isPending && (
        <div className="space-y-4">
          <div className="p-6 rounded-2xl bg-[var(--exec-surface)] border border-[var(--exec-border)] shadow-xs space-y-4">
            <div className="space-y-1.5">
              <label className="text-xs font-heading font-bold text-[var(--exec-text)] uppercase tracking-wider">
                What would you like to achieve?
              </label>
              <p className="text-xs text-[var(--exec-text-muted)]">
                State your goal, target skill, and desired timeline (e.g. &ldquo;in 2 days&rdquo;, &ldquo;in 7 days&rdquo;).
              </p>
            </div>

            <div className="relative">
              <textarea
                value={goalText}
                onChange={(e) => setGoalText(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    handleSubmitGoal();
                  }
                }}
                disabled={isPending}
                placeholder="e.g. I need to learn coding basics in 2 days according to my level..."
                className="w-full h-28 px-4 py-3 text-sm bg-[var(--exec-surface-secondary)] border border-[var(--exec-border)] rounded-xl text-[var(--exec-text)] placeholder-[var(--exec-text-muted)] focus:outline-none focus:ring-2 focus:ring-sky-500/30 resize-none transition-all"
              />
              <div className="absolute right-3 bottom-3">
                <Button
                  variant="primary"
                  size="sm"
                  onClick={() => handleSubmitGoal()}
                  disabled={!goalText.trim() || isPending}
                  className="gap-1.5 shadow-sm font-medium"
                >
                  <Sparkles className="w-3.5 h-3.5" />
                  <span>Build Learning Roadmap</span>
                </Button>
              </div>
            </div>

            {/* Curated Quick Goal Chips */}
            <div className="pt-2 border-t border-[var(--exec-border)] space-y-2">
              <span className="text-[11px] font-mono text-[var(--exec-text-muted)] uppercase tracking-wider block">
                Popular Learning Goals:
              </span>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {CURATED_GOALS.map((g, idx) => (
                  <button
                    key={idx}
                    type="button"
                    onClick={() => {
                      setGoalText(g.text);
                      handleSubmitGoal(g.text);
                    }}
                    className="p-3 text-left rounded-xl bg-[var(--exec-surface-secondary)] hover:bg-sky-500/10 hover:border-sky-500/30 border border-[var(--exec-border)] transition-all cursor-pointer group"
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-semibold text-[var(--exec-text)] group-hover:text-sky-600 dark:group-hover:text-sky-400">
                        {g.label}
                      </span>
                      <Badge variant="slate" className="text-[9px]">
                        {g.category}
                      </Badge>
                    </div>
                    <p className="text-[11px] text-[var(--exec-text-muted)] line-clamp-1 mt-1">
                      {g.text}
                    </p>
                  </button>
                ))}
              </div>
            </div>

            {/* Resume Active Journey Button */}
            <div className="flex items-center justify-between pt-2">
              <Button
                variant="ghost"
                size="sm"
                onClick={handleResumeJourney}
                disabled={isPending}
                className="text-xs text-sky-600 dark:text-sky-400 hover:bg-sky-500/10 gap-1.5"
              >
                <Compass className="w-3.5 h-3.5" />
                Resume Previously Active Journey
              </Button>
            </div>
          </div>

          {resumeNotice && (
            <div className="p-3.5 rounded-xl bg-sky-500/10 border border-sky-500/30 text-xs text-sky-700 dark:text-sky-300 flex items-center gap-2">
              <Info className="w-4 h-4 shrink-0 text-sky-500" />
              <span>{resumeNotice}</span>
            </div>
          )}
        </div>
      )}

      {/* 3. EXPERIENCE A: SEQUENTIAL ORCHESTRATION RUNNING STATE */}
      {isPending && (
        <div className="p-8 rounded-2xl bg-[var(--exec-surface)] border border-[var(--exec-border)] shadow-sm space-y-6 animate-in fade-in duration-300">
          <div className="space-y-1 text-center max-w-md mx-auto">
            <h2 className="text-base font-heading font-bold text-[var(--exec-text)]">
              Building Your Custom Learning Plan
            </h2>
            <p className="text-xs text-[var(--exec-text-muted)] font-sans">
              Analyzing your goal against verified telemetry to construct an actionable roadmap.
            </p>
          </div>

          {/* Sequential Stage Progress Flow (Only ONE active at a time) */}
          <div className="max-w-lg mx-auto space-y-3">
            {/* Stage 1: Understanding Goal */}
            <div className={`p-3.5 rounded-xl border transition-all flex items-center gap-3.5 ${
              currentStage === 'STAGE_1_UNDERSTANDING'
                ? 'bg-sky-500/10 border-sky-500/40 shadow-xs'
                : currentStage === 'STAGE_READY' || currentStage === 'STAGE_2_ASSESSING' || currentStage === 'STAGE_3_DESIGNING' || currentStage === 'STAGE_4_PREPARING'
                ? 'bg-emerald-500/5 border-emerald-500/30'
                : 'bg-[var(--exec-surface-secondary)] border-[var(--exec-border)] opacity-50'
            }`}>
              <div className="shrink-0">
                {currentStage === 'STAGE_1_UNDERSTANDING' ? (
                  <RefreshCw className="w-4 h-4 text-sky-600 animate-spin" />
                ) : (
                  <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                )}
              </div>
              <div className="space-y-0.5">
                <div className="text-xs font-semibold text-[var(--exec-text)]">
                  1. Understanding your goal
                </div>
                <div className="text-[11px] text-[var(--exec-text-muted)]">
                  Analyzing target skill scope, timeframe constraints, and learning objectives.
                </div>
              </div>
            </div>

            {/* Stage 2: Checking Level */}
            <div className={`p-3.5 rounded-xl border transition-all flex items-center gap-3.5 ${
              currentStage === 'STAGE_2_ASSESSING'
                ? 'bg-sky-500/10 border-sky-500/40 shadow-xs'
                : currentStage === 'STAGE_3_DESIGNING' || currentStage === 'STAGE_4_PREPARING' || currentStage === 'STAGE_READY'
                ? 'bg-emerald-500/5 border-emerald-500/30'
                : 'bg-[var(--exec-surface-secondary)] border-[var(--exec-border)] opacity-50'
            }`}>
              <div className="shrink-0">
                {currentStage === 'STAGE_2_ASSESSING' ? (
                  <RefreshCw className="w-4 h-4 text-sky-600 animate-spin" />
                ) : currentStage === 'STAGE_3_DESIGNING' || currentStage === 'STAGE_4_PREPARING' || currentStage === 'STAGE_READY' ? (
                  <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                ) : (
                  <div className="w-4 h-4 rounded-full border border-[var(--exec-border)]" />
                )}
              </div>
              <div className="space-y-0.5">
                <div className="text-xs font-semibold text-[var(--exec-text)]">
                  2. Checking your current level
                </div>
                <div className="text-[11px] text-[var(--exec-text-muted)]">
                  Reviewing verified skills, GitHub activity, LeetCode data, and logged mistake patterns.
                </div>
              </div>
            </div>

            {/* Stage 3: Designing Roadmap */}
            <div className={`p-3.5 rounded-xl border transition-all flex items-center gap-3.5 ${
              currentStage === 'STAGE_3_DESIGNING'
                ? 'bg-sky-500/10 border-sky-500/40 shadow-xs'
                : currentStage === 'STAGE_4_PREPARING' || currentStage === 'STAGE_READY'
                ? 'bg-emerald-500/5 border-emerald-500/30'
                : 'bg-[var(--exec-surface-secondary)] border-[var(--exec-border)] opacity-50'
            }`}>
              <div className="shrink-0">
                {currentStage === 'STAGE_3_DESIGNING' ? (
                  <RefreshCw className="w-4 h-4 text-sky-600 animate-spin" />
                ) : currentStage === 'STAGE_4_PREPARING' || currentStage === 'STAGE_READY' ? (
                  <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                ) : (
                  <div className="w-4 h-4 rounded-full border border-[var(--exec-border)]" />
                )}
              </div>
              <div className="space-y-0.5">
                <div className="text-xs font-semibold text-[var(--exec-text)]">
                  3. Designing your roadmap
                </div>
                <div className="text-[11px] text-[var(--exec-text-muted)]">
                  Structuring realistic milestone steps, practical exercises, and verification criteria.
                </div>
              </div>
            </div>

            {/* Stage 4: Preparing First Step */}
            <div className={`p-3.5 rounded-xl border transition-all flex items-center gap-3.5 ${
              currentStage === 'STAGE_4_PREPARING'
                ? 'bg-sky-500/10 border-sky-500/40 shadow-xs'
                : currentStage === 'STAGE_READY'
                ? 'bg-emerald-500/5 border-emerald-500/30'
                : 'bg-[var(--exec-surface-secondary)] border-[var(--exec-border)] opacity-50'
            }`}>
              <div className="shrink-0">
                {currentStage === 'STAGE_4_PREPARING' ? (
                  <RefreshCw className="w-4 h-4 text-sky-600 animate-spin" />
                ) : (
                  <div className="w-4 h-4 rounded-full border border-[var(--exec-border)]" />
                )}
              </div>
              <div className="space-y-0.5">
                <div className="text-xs font-semibold text-[var(--exec-text)]">
                  4. Preparing your next action
                </div>
                <div className="text-[11px] text-[var(--exec-text-muted)]">
                  Finalizing the roadmap and queuing your immediate starting exercise.
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Error Banner */}
      {errorMessage && (
        <div className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-600 dark:text-rose-400 text-xs flex items-center gap-2">
          <AlertTriangle className="w-4 h-4 shrink-0" />
          <span>{errorMessage}</span>
        </div>
      )}

      {/* Clarification Gate (Only when genuinely ambiguous) */}
      {runResult?.status === 'NEEDS_CLARIFICATION' && runResult.clarificationQuestions && (
        <div className="p-6 rounded-2xl bg-amber-500/10 border border-amber-500/30 space-y-5 animate-in fade-in duration-200">
          <div className="space-y-1">
            <div className="flex items-center gap-2 text-xs font-heading font-bold text-amber-800 dark:text-amber-400">
              <HelpCircle className="w-4 h-4" />
              <span>Clarification Needed to Personalize Your Plan</span>
            </div>
            <p className="text-xs text-[var(--exec-text)] leading-relaxed">
              To tailor your study schedule precisely, please select your preferred answer for each question below:
            </p>
          </div>

          <div className="space-y-4">
            {runResult.clarificationQuestions.map((q, idx) => {
              const selectedAnswer = selectedClarifications[idx];

              return (
                <div key={idx} className="p-4 rounded-xl bg-[var(--exec-surface)] border border-amber-500/20 space-y-2.5">
                  <div className="flex items-center justify-between gap-2">
                    <p className="text-xs font-semibold text-[var(--exec-text)]">
                      {idx + 1}. {q.question}
                    </p>
                    {selectedAnswer && (
                      <Badge variant="emerald" className="text-[9px] shrink-0">
                        Selected
                      </Badge>
                    )}
                  </div>

                  {q.suggestedOptions && (
                    <div className="flex flex-wrap gap-2 pt-1">
                      {q.suggestedOptions.map((opt, oIdx) => {
                        const isSelected = selectedAnswer === opt;
                        return (
                          <button
                            key={oIdx}
                            type="button"
                            onClick={() => {
                              setSelectedClarifications((prev) => ({
                                ...prev,
                                [idx]: opt,
                              }));
                            }}
                            className={`px-3 py-1.5 rounded-xl text-xs font-sans transition-all cursor-pointer border text-left ${
                              isSelected
                                ? 'bg-sky-600 hover:bg-sky-700 text-white border-sky-600 font-medium shadow-xs ring-1 ring-sky-500/30'
                                : 'bg-[var(--exec-surface-secondary)] hover:bg-sky-500/10 text-[var(--exec-text)] border-[var(--exec-border)] hover:border-sky-500/30'
                            }`}
                          >
                            <span className="flex items-center gap-1.5">
                              {isSelected && <Check className="w-3.5 h-3.5 shrink-0" />}
                              <span>{opt}</span>
                            </span>
                          </button>
                        );
                      })}
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          {/* Unified Multi-Answer Submission */}
          <div className="pt-3 border-t border-amber-500/20 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <span className="text-[11px] text-[var(--exec-text-muted)] font-sans">
              {Object.keys(selectedClarifications).length} of {runResult.clarificationQuestions.length} answered
            </span>
            <Button
              variant="primary"
              size="sm"
              disabled={Object.keys(selectedClarifications).length === 0 || isPending}
              onClick={() => {
                const answers = Object.entries(selectedClarifications)
                  .sort(([a], [b]) => Number(a) - Number(b))
                  .map(([_, v]) => v)
                  .filter(Boolean);
                const combined = `${goalText.trim()} — ${answers.join(' — ')}`;
                setGoalText(combined);
                handleSubmitGoal(combined);
              }}
              className="font-medium gap-1.5 shadow-sm px-4"
            >
              <Sparkles className="w-3.5 h-3.5" />
              <span>Submit Preferences & Build Roadmap</span>
            </Button>
          </div>
        </div>
      )}

      {/* 4. EXPERIENCE B: REAL LEARNING ROADMAP (Clean, Apple-Grade Visual Hierarchy) */}
      {runResult && (runResult.status === 'COMPLETED' || runResult.status === 'WAITING_FOR_APPROVAL') && (
        <div className="space-y-6">

          {/* Roadmap Overview Hero Card */}
          <div className="p-6 rounded-2xl bg-[var(--exec-surface)] border border-[var(--exec-border)] shadow-xs space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div className="space-y-1">
                <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-sky-600 dark:text-sky-400 block">
                  {runResult.goalUnderstanding?.timeframe 
                    ? `Your ${runResult.goalUnderstanding.timeframe} Roadmap`
                    : 'Personalized Learning Roadmap'}
                </span>
                <h2 className="text-lg font-heading font-bold text-[var(--exec-text)]">
                  {runResult.goalUnderstanding?.objective || runResult.goalUnderstanding?.originalGoal || goalText}
                </h2>
              </div>

              <div className="flex flex-wrap items-center gap-2">
                {runResult.goalUnderstanding?.targetSkill && (
                  <Badge variant="indigo" className="text-xs">
                    {runResult.goalUnderstanding.targetSkill}
                  </Badge>
                )}
                <Badge variant="slate" className="text-xs font-mono">
                  <Clock className="w-3 h-3 mr-1" />
                  {durationLabel}
                </Badge>
                <Badge variant="emerald" className="text-xs">
                  {completedStepsCount}/{steps.length} Steps Completed ({progressPercent}%)
                </Badge>
              </div>
            </div>

            {/* Progress Bar */}
            <div className="w-full bg-[var(--exec-surface-secondary)] rounded-full h-2 overflow-hidden border border-[var(--exec-border)]">
              <div 
                className="bg-emerald-500 h-full transition-all duration-500 rounded-full"
                style={{ width: `${progressPercent}%` }}
              />
            </div>
          </div>

          {/* Starting Point & Verified Level Card */}
          {runResult.studentAssessment && (
            <div className="p-6 rounded-2xl bg-[var(--exec-surface)] border border-[var(--exec-border)] shadow-xs space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="text-xs font-heading font-bold uppercase tracking-wider text-[var(--exec-text)] flex items-center gap-2">
                  <Award className="w-4 h-4 text-amber-500" />
                  Your Starting Point & Verified Level
                </h3>
                <Badge variant="slate" className="text-[10px]">
                  {runResult.studentAssessment.overallConfidence === 'HIGH' ? 'Verified Telemetry' : 'Baseline Assessment'}
                </Badge>
              </div>

              {/* Assessment Narrative */}
              <p className="text-xs text-[var(--exec-text)] leading-relaxed">
                {runResult.studentAssessment.assessmentSummary}
              </p>

              {/* Strengths & Growth Areas */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-1">
                {/* Strengths */}
                <div className="p-3 rounded-xl bg-[var(--exec-surface-secondary)] border border-[var(--exec-border)] space-y-1">
                  <span className="text-[10px] font-mono font-bold uppercase text-emerald-600 dark:text-emerald-400 block">
                    Verified Strengths
                  </span>
                  {runResult.studentAssessment.supportedStrengths.length > 0 ? (
                    <div className="flex flex-wrap gap-1">
                      {runResult.studentAssessment.supportedStrengths.map((s, i) => (
                        <Badge key={i} variant="emerald" className="text-[10px]">{s}</Badge>
                      ))}
                    </div>
                  ) : (
                    <span className="text-xs text-[var(--exec-text-muted)]">Building initial baseline</span>
                  )}
                </div>

                {/* Developing Areas */}
                <div className="p-3 rounded-xl bg-[var(--exec-surface-secondary)] border border-[var(--exec-border)] space-y-1">
                  <span className="text-[10px] font-mono font-bold uppercase text-sky-600 dark:text-sky-400 block">
                    Developing Focus
                  </span>
                  {runResult.studentAssessment.developingAreas.length > 0 ? (
                    <div className="flex flex-wrap gap-1">
                      {runResult.studentAssessment.developingAreas.map((s, i) => (
                        <Badge key={i} variant="cyan" className="text-[10px]">{s}</Badge>
                      ))}
                    </div>
                  ) : (
                    <span className="text-xs text-[var(--exec-text-muted)]">Core fundamentals</span>
                  )}
                </div>

                {/* Target Gaps */}
                <div className="p-3 rounded-xl bg-[var(--exec-surface-secondary)] border border-[var(--exec-border)] space-y-1">
                  <span className="text-[10px] font-mono font-bold uppercase text-amber-600 dark:text-amber-400 block">
                    Target Growth Gaps
                  </span>
                  {runResult.studentAssessment.evidenceGaps.length > 0 ? (
                    <div className="flex flex-wrap gap-1">
                      {runResult.studentAssessment.evidenceGaps.map((s, i) => (
                        <Badge key={i} variant="amber" className="text-[10px]">{s}</Badge>
                      ))}
                    </div>
                  ) : (
                    <span className="text-xs text-[var(--exec-text-muted)]">Practical application recommended</span>
                  )}
                </div>
              </div>

              {/* Inspected Evidence Sources */}
              {runResult.studentAssessment.recentActivitySummary && (
                <div className="pt-2 border-t border-[var(--exec-border)] space-y-1.5 text-[11px] text-[var(--exec-text-muted)]">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="font-mono text-[10px] uppercase font-semibold">Evidence Sources Inspected:</span>
                    {runResult.studentAssessment.recentActivitySummary.activeSources && runResult.studentAssessment.recentActivitySummary.activeSources.length > 0 ? (
                      runResult.studentAssessment.recentActivitySummary.activeSources.map((src, i) => (
                        <span key={i} className="px-2 py-0.5 rounded-md bg-[var(--exec-surface-secondary)] border border-[var(--exec-border)] text-[var(--exec-text)] font-mono text-[10px]">
                          {src}
                        </span>
                      ))
                    ) : (
                      <span className="text-[10px] font-mono text-[var(--exec-text-muted)] italic">
                        Initial baseline (no prior telemetry records found)
                      </span>
                    )}
                  </div>

                  {(!runResult.studentAssessment.recentActivitySummary.hasRecentGitHubActivity ||
                    !runResult.studentAssessment.recentActivitySummary.hasRecentLeetCodeActivity) && (
                    <p className="text-[10px] text-[var(--exec-text-muted)] font-sans italic">
                      ℹ External telemetry ({[!runResult.studentAssessment.recentActivitySummary.hasRecentGitHubActivity && 'GitHub', !runResult.studentAssessment.recentActivitySummary.hasRecentLeetCodeActivity && 'LeetCode'].filter(Boolean).join(', ')}) is not connected — roadmap is grounded on available local profile & activity evidence.
                    </p>
                  )}
                </div>
              )}
            </div>
          )}

          {/* Why This Roadmap Card */}
          {runResult.learningDecision && (
            <div className="p-5 rounded-2xl bg-sky-500/5 border border-sky-500/20 space-y-1.5">
              <div className="flex items-center gap-2 text-xs font-heading font-bold text-sky-700 dark:text-sky-300">
                <Zap className="w-4 h-4 text-sky-500" />
                <span>Why This Roadmap?</span>
              </div>
              <p className="text-xs text-[var(--exec-text)] leading-relaxed">
                {runResult.learningDecision.rationale}
              </p>
            </div>
          )}

          {/* Visual Learning Roadmap — Day-by-Day Cards or Flat Milestone List */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-heading font-bold uppercase tracking-wider text-[var(--exec-text)] flex items-center gap-2">
                <ListChecks className="w-4 h-4 text-sky-500" />
                {isDayByDayPlan(steps)
                  ? `Day-by-Day Roadmap (${steps.length} ${steps.length === 1 ? 'Day' : 'Days'})`
                  : `Your Learning Milestones (${steps.length} Steps)`}
              </h3>
              <span className="text-xs font-mono text-[var(--exec-text-muted)]">
                {durationLabel} Total Effort
              </span>
            </div>

            {isDayByDayPlan(steps) ? (
              /* ================================================================
                 DAY-BY-DAY ROADMAP CARDS
                 ================================================================ */
              <div className="space-y-4">
                {steps.map((step, sIdx) => {
                  const meta = step.metadata as Record<string, any>;
                  const dayNum = (meta?.dayNumber as number) ?? sIdx + 1;
                  const topic = (meta?.topic as string) ?? step.title;
                  const learnContent = (meta?.learnContent as string) ?? step.description;
                  const practiceProblems = (meta?.practiceProblems as number) ?? 3;
                  const reviewActivity = (meta?.reviewActivity as string) ?? 'Review notes';
                  const evidenceRationale = (meta?.evidenceRationale as string) ?? step.rationale;
                  const aiMinutes = (meta?.aiEstimatedMinutes as number) ?? (step.estimatedEffort?.estimatedMinutes ?? 60);
                  const aiPriority = step.priority as DayPriority;
                  const isCompleted = step.status === 'COMPLETED';

                  const edit = dayEdits[step.id] ?? { isEdited: false };
                  const displayMinutes = edit.editedMinutes ?? aiMinutes;
                  const displayPriority = edit.editedPriority ?? aiPriority;

                  const updateEdit = (patch: Partial<DayEditState>) =>
                    setDayEdits((prev) => ({
                      ...prev,
                      [step.id]: { ...prev[step.id], isEdited: true, ...patch },
                    }));

                  const cyclePriority = () => {
                    const idx = PRIORITY_CYCLE.indexOf(displayPriority);
                    updateEdit({ editedPriority: PRIORITY_CYCLE[(idx + 1) % PRIORITY_CYCLE.length] });
                  };

                  return (
                    <div
                      key={step.id}
                      className={`rounded-2xl border transition-all overflow-hidden ${
                        isCompleted
                          ? 'border-emerald-500/30 bg-emerald-500/5'
                          : sIdx === 0 && !isCompleted
                          ? 'border-sky-500/40 bg-[var(--exec-surface)] shadow-sm ring-1 ring-sky-500/10'
                          : 'border-[var(--exec-border)] bg-[var(--exec-surface)]'
                      }`}
                    >
                      {/* Day Header Bar */}
                      <div className={`px-5 py-3 flex items-center justify-between gap-3 border-b ${
                        isCompleted
                          ? 'border-emerald-500/20 bg-emerald-500/10'
                          : sIdx === 0 && !isCompleted
                          ? 'border-sky-500/20 bg-sky-500/5'
                          : 'border-[var(--exec-border)] bg-[var(--exec-surface-secondary)]'
                      }`}>
                        <div className="flex items-center gap-3">
                          <span className={`w-8 h-8 rounded-xl text-xs font-mono font-bold flex items-center justify-center shrink-0 ${
                            isCompleted
                              ? 'bg-emerald-500 text-white'
                              : sIdx === 0
                              ? 'bg-sky-500 text-white'
                              : 'bg-[var(--exec-surface)] text-[var(--exec-text-muted)] border border-[var(--exec-border)]'
                          }`}>
                            {isCompleted ? <Check className="w-4 h-4" /> : `D${dayNum}`}
                          </span>
                          <div>
                            <div className="text-xs font-heading font-bold text-[var(--exec-text)] leading-tight">
                              Day {dayNum} — {topic}
                            </div>
                            {sIdx === 0 && !isCompleted && (
                              <span className="text-[10px] font-mono text-sky-600 dark:text-sky-400">Start Here</span>
                            )}
                          </div>
                        </div>

                        {/* Time + Priority badges — both editable */}
                        <div className="flex items-center gap-2 shrink-0 flex-wrap justify-end">
                          {/* Editable time */}
                          <div className="flex items-center gap-1 px-2 py-1 rounded-lg bg-[var(--exec-surface)] border border-[var(--exec-border)] text-[11px] font-mono">
                            <Clock className="w-3 h-3 text-[var(--exec-text-muted)] shrink-0" />
                            <button
                              type="button"
                              title="Decrease by 15 min"
                              onClick={() => updateEdit({ editedMinutes: Math.max(15, displayMinutes - 15) })}
                              className="text-[var(--exec-text-muted)] hover:text-sky-500 transition-colors p-0.5"
                            >
                              <Minus className="w-2.5 h-2.5" />
                            </button>
                            <span className={`font-bold min-w-[32px] text-center ${
                              edit.isEdited && edit.editedMinutes !== undefined
                                ? 'text-sky-600 dark:text-sky-400'
                                : 'text-[var(--exec-text)]'
                            }`}>
                              {displayMinutes}m
                            </span>
                            <button
                              type="button"
                              title="Increase by 15 min"
                              onClick={() => updateEdit({ editedMinutes: Math.min(240, displayMinutes + 15) })}
                              className="text-[var(--exec-text-muted)] hover:text-sky-500 transition-colors p-0.5"
                            >
                              <Plus className="w-2.5 h-2.5" />
                            </button>
                          </div>

                          {/* Editable priority */}
                          <button
                            type="button"
                            title="Click to cycle priority"
                            onClick={cyclePriority}
                            className={`px-2.5 py-1 rounded-lg border text-[10px] font-mono font-bold uppercase tracking-wider cursor-pointer transition-all hover:scale-105 ${
                              PRIORITY_COLORS[displayPriority]
                            } ${ edit.isEdited && edit.editedPriority ? 'ring-1 ring-offset-1 ring-current' : '' }`}
                          >
                            {displayPriority}
                          </button>

                          {/* Edit indicator */}
                          {edit.isEdited && (
                            <span className="text-[9px] font-mono text-sky-500 font-bold uppercase tracking-wider bg-sky-500/10 px-1.5 py-0.5 rounded-md border border-sky-500/20">
                              Your Edit
                            </span>
                          )}
                        </div>
                      </div>

                      {/* Day Body */}
                      <div className="px-5 py-4 space-y-3 text-xs">
                        {/* Learn */}
                        <div className="flex items-start gap-2.5">
                          <BookOpen className="w-3.5 h-3.5 text-indigo-500 shrink-0 mt-0.5" />
                          <div>
                            <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-400 block mb-0.5">Learn</span>
                            <p className="text-[var(--exec-text)] leading-relaxed">{learnContent}</p>
                          </div>
                        </div>

                        {/* Practice */}
                        <div className="flex items-start gap-2.5">
                          <FlaskConical className="w-3.5 h-3.5 text-sky-500 shrink-0 mt-0.5" />
                          <div>
                            <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-sky-600 dark:text-sky-400 block mb-0.5">Practice</span>
                            <p className="text-[var(--exec-text)] font-semibold">
                              {practiceProblems} problem{practiceProblems !== 1 ? 's' : ''}
                            </p>
                          </div>
                        </div>

                        {/* Review */}
                        <div className="flex items-start gap-2.5">
                          <RefreshCw className="w-3.5 h-3.5 text-emerald-500 shrink-0 mt-0.5" />
                          <div>
                            <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-emerald-600 dark:text-emerald-400 block mb-0.5">Review</span>
                            <p className="text-[var(--exec-text)] leading-relaxed">{reviewActivity}</p>
                          </div>
                        </div>

                        {/* Evidence rationale */}
                        {evidenceRationale && (
                          <div className="pt-1 border-t border-[var(--exec-border)] flex items-start gap-2">
                            <Zap className="w-3 h-3 text-amber-500 shrink-0 mt-0.5" />
                            <p className="text-[10px] text-[var(--exec-text-muted)] leading-relaxed italic">
                              <span className="font-semibold not-italic text-amber-600 dark:text-amber-400">Why this time: </span>
                              {evidenceRationale}
                              {edit.isEdited && (
                                <span className="ml-1 not-italic font-bold text-sky-600 dark:text-sky-400">
                                  [AI estimate: {aiMinutes}m / Your edit: {displayMinutes}m]
                                </span>
                              )}
                            </p>
                          </div>
                        )}

                        {/* Complete step action */}
                        {!isCompleted && (
                          <div className="pt-2 flex flex-col sm:flex-row items-stretch sm:items-center gap-2 border-t border-[var(--exec-border)]">
                            <input
                              type="text"
                              placeholder="Optional notes on today's work..."
                              value={stepNotesMap[step.id] || ''}
                              onChange={(e) =>
                                setStepNotesMap((prev) => ({ ...prev, [step.id]: e.target.value }))
                              }
                              className="flex-1 px-3.5 py-2 rounded-xl bg-[var(--exec-surface-secondary)] border border-[var(--exec-border)] text-xs text-[var(--exec-text)] placeholder:text-[var(--exec-text-muted)] focus:outline-none focus:ring-1 focus:ring-sky-500 font-sans"
                            />
                            <Button
                              variant="primary"
                              size="sm"
                              disabled={completingStepId === step.id || isPending}
                              onClick={() => handleCompleteStep(step.id)}
                              className="text-xs shrink-0 font-medium px-4"
                            >
                              {completingStepId === step.id ? (
                                <><RefreshCw className="w-3.5 h-3.5 mr-1.5 animate-spin" />Recording...</>
                              ) : (
                                <><CheckCircle2 className="w-3.5 h-3.5 mr-1.5" />Mark Day {dayNum} Done</>
                              )}
                            </Button>
                          </div>
                        )}

                        {/* Step feedback */}
                        {stepFeedbackMap[step.id] && (
                          <div className="mt-2 p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-xs flex items-center gap-2 text-emerald-700 dark:text-emerald-300">
                            <CheckCircle2 className="w-4 h-4 shrink-0" />
                            <span>Day {dayNum} completed & logged to your profile.</span>
                          </div>
                        )}
                      </div>
                    </div>
                  );

                })}
              </div>
            ) : (
              /* ================================================================
                 FLAT MILESTONE LIST (non-timeframe goals)
                 ================================================================ */
              <div className="space-y-4">
                {steps.map((step, sIdx) => {
                  const isCompleted = step.status === 'COMPLETED';
                  const isNextAction = !isCompleted && (activeStepId === step.id || (!activeStepId && sIdx === 0));
                  const feedback = stepFeedbackMap[step.id];
                  const isCompleting = completingStepId === step.id;
                  const estMinutes = step.estimatedEffort?.estimatedMinutes || 45;

                  return (
                    <div
                      key={step.id || sIdx}
                      className={`p-5 rounded-2xl border transition-all ${
                        isCompleted
                          ? 'bg-emerald-500/5 border-emerald-500/30'
                          : isNextAction
                          ? 'bg-[var(--exec-surface)] border-sky-500/40 shadow-sm ring-1 ring-sky-500/20'
                          : 'bg-[var(--exec-surface)] border-[var(--exec-border)] opacity-85'
                      }`}
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex items-start gap-3">
                          <span className={`w-7 h-7 rounded-full text-xs font-mono font-bold flex items-center justify-center shrink-0 mt-0.5 ${
                            isCompleted ? 'bg-emerald-500/20 text-emerald-600 dark:text-emerald-400'
                            : isNextAction ? 'bg-sky-500 text-white shadow-xs'
                            : 'bg-[var(--exec-surface-secondary)] text-[var(--exec-text-muted)] border border-[var(--exec-border)]'
                          }`}>
                            {isCompleted ? <Check className="w-4 h-4" /> : step.order || sIdx + 1}
                          </span>
                          <div className="space-y-1">
                            <div className="flex flex-wrap items-center gap-2">
                              <span className="text-sm font-semibold text-[var(--exec-text)]">{step.title}</span>
                              {isNextAction && <Badge variant="cyan" className="text-[10px] font-sans">Next Action</Badge>}
                            </div>
                            {step.targetSkill && (
                              <span className="text-[11px] font-mono text-sky-600 dark:text-sky-400 block">Topic: {step.targetSkill}</span>
                            )}
                          </div>
                        </div>
                        <div className="flex items-center gap-2 shrink-0">
                          <Badge variant="slate" className="text-[10px] font-mono">
                            <Clock className="w-3 h-3 mr-1" />~ {estMinutes}m
                          </Badge>
                          <Badge variant={isCompleted ? 'emerald' : isNextAction ? 'cyan' : 'slate'} className="text-[10px] uppercase font-sans">
                            {isCompleted ? 'Completed' : 'To Do'}
                          </Badge>
                        </div>
                      </div>

                      <div className="mt-3.5 ml-10 space-y-3 text-xs">
                        <div className="text-[var(--exec-text)] leading-relaxed">
                          <strong className="text-[10px] font-mono uppercase text-[var(--exec-text-muted)] block mb-0.5">What you&apos;ll do:</strong>
                          {step.description}
                        </div>
                        {step.successCriteria && step.successCriteria.length > 0 && (
                          <div className="p-3 rounded-xl bg-[var(--exec-surface-secondary)] border border-[var(--exec-border)]">
                            <span className="font-mono font-bold text-[10px] uppercase text-[var(--exec-text-muted)] block mb-1">Expected Outcome:</span>
                            <ul className="list-disc list-inside space-y-0.5 text-[var(--exec-text)]">
                              {step.successCriteria.map((c, idx) => <li key={idx}>{c}</li>)}
                            </ul>
                          </div>
                        )}
                        {!isCompleted && (
                          <div className="pt-2 flex flex-col sm:flex-row items-stretch sm:items-center gap-2">
                            <input
                              type="text"
                              placeholder="Optional reflection or notes on your work..."
                              value={stepNotesMap[step.id] || ''}
                              onChange={(e) => setStepNotesMap((prev) => ({ ...prev, [step.id]: e.target.value }))}
                              className="flex-1 px-3.5 py-2 rounded-xl bg-[var(--exec-surface-secondary)] border border-[var(--exec-border)] text-xs text-[var(--exec-text)] placeholder:text-[var(--exec-text-muted)] focus:outline-none focus:ring-1 focus:ring-sky-500 font-sans"
                            />
                            <Button
                              variant="primary" size="sm"
                              disabled={isCompleting || isPending}
                              onClick={() => handleCompleteStep(step.id)}
                              className="text-xs shrink-0 font-medium px-4"
                            >
                              {isCompleting ? <><RefreshCw className="w-3.5 h-3.5 mr-1.5 animate-spin" />Recording...</> : <><CheckCircle2 className="w-3.5 h-3.5 mr-1.5" />Complete Step & Log Progress</>}
                            </Button>
                          </div>
                        )}
                        {feedback && (
                          <div className="mt-3 p-3.5 rounded-xl bg-emerald-500/10 border border-emerald-500/30 space-y-2">
                            <div className="flex items-center justify-between">
                              <span className="font-sans font-bold text-xs text-emerald-800 dark:text-emerald-300 flex items-center gap-1.5">
                                <Sparkles className="w-4 h-4 text-emerald-600" />Milestone Completed & Verified
                              </span>
                              <Badge variant="emerald" className="text-[10px]">Progress Recorded</Badge>
                            </div>
                            <p className="text-xs text-[var(--exec-text)]">Your progress has been calibrated into your profile and trajectory models.</p>
                            {feedback.nextLearningDecision && (
                              <div className="p-2.5 rounded-lg bg-[var(--exec-surface)] border border-emerald-500/20 text-xs">
                                <span className="font-mono text-[10px] uppercase font-bold text-sky-600 dark:text-sky-400 block mb-0.5">Next Pedagogical Recommendation:</span>
                                <span>{feedback.nextLearningDecision.primaryObjective}</span>
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            )}

            {/* ADD TO LEARNING PATH BUTTON */}
            <div className="mt-4 p-5 rounded-2xl bg-[var(--exec-surface-secondary)] border border-[var(--exec-border)] space-y-3">
              <div className="flex items-start gap-3">
                <div className="p-2 rounded-lg bg-sky-500/10 border border-sky-500/20 text-sky-600 dark:text-sky-400 shrink-0">
                  <BookMarked className="w-4 h-4" />
                </div>
                <div className="space-y-1">
                  <p className="text-xs font-heading font-bold text-[var(--exec-text)]">
                    Ready to save this roadmap?
                  </p>
                  <p className="text-[11px] text-[var(--exec-text-muted)] leading-relaxed">
                    Save this personalized roadmap directly into your active Learning Path to track daily practice, schedule reminders, and see today&apos;s tasks on your dashboard.
                    {Object.values(dayEdits).some((e) => e.isEdited) && (
                      <span className="ml-1 text-sky-600 dark:text-sky-400 font-semibold">
                        ({Object.values(dayEdits).filter((e) => e.isEdited).length} day(s) customized)
                      </span>
                    )}
                  </p>
                </div>
              </div>

              {savePathResult?.success ? (
                <div className="p-4 rounded-xl bg-emerald-500/10 border border-emerald-500/30 space-y-3">
                  <div className="flex items-center gap-2 text-emerald-700 dark:text-emerald-300 font-bold text-xs">
                    <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                    <span>Saved to Your Learning Path!</span>
                  </div>
                  <p className="text-[11px] text-[var(--exec-text-muted)]">
                    Your personalized plan is now active across your account and dashboard.
                  </p>
                  <div className="flex items-center gap-2 pt-1">
                    <Link href="/learning-path" className="flex-1">
                      <Button
                        variant="primary"
                        size="sm"
                        className="w-full justify-center gap-1.5 text-xs font-semibold bg-emerald-600 hover:bg-emerald-700 text-white"
                      >
                        <Milestone className="w-3.5 h-3.5" />
                        Open Learning Path
                        <ArrowRight className="w-3.5 h-3.5" />
                      </Button>
                    </Link>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setSavePathResult(null)}
                      className="text-xs text-[var(--exec-text-muted)]"
                    >
                      Dismiss
                    </Button>
                  </div>
                </div>
              ) : (
                <div className="space-y-2">
                  {savePathResult?.error && (
                    <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/30 text-xs text-rose-700 dark:text-rose-400">
                      {savePathResult.error}
                    </div>
                  )}
                  <Button
                    variant="primary"
                    size="sm"
                    disabled={isSavingPath || isPending}
                    onClick={handleSaveToLearningPath}
                    className="w-full justify-center gap-2 font-medium shadow-sm bg-sky-600 hover:bg-sky-700 text-white"
                  >
                    {isSavingPath ? (
                      <>
                        <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                        Saving to Learning Path...
                      </>
                    ) : (
                      <>
                        <BookMarked className="w-3.5 h-3.5" />
                        Add to Learning Path
                      </>
                    )}
                  </Button>
                </div>
              )}
            </div>
          </div>


          {/* 5. Contextual Phase 5 Human Approval Gate */}
          {runResult.approvalProposal && approvalStatus !== 'APPROVED' && approvalStatus !== 'REJECTED' && (
            <div className="p-5 rounded-2xl bg-amber-500/10 border border-amber-500/30 space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2 text-xs font-heading font-bold text-amber-800 dark:text-amber-400">
                  <ShieldCheck className="w-4 h-4 text-amber-600" />
                  <span>Want me to add this milestone to your Tasks?</span>
                </div>
                <Badge variant="amber" className="text-[10px] font-sans">
                  Optional Confirmation
                </Badge>
              </div>

              <div className="p-3.5 rounded-xl bg-[var(--exec-surface)] border border-amber-500/20 text-xs space-y-1">
                <div className="font-semibold text-[var(--exec-text)]">
                  {runResult.approvalProposal.input.title}
                </div>
                {runResult.approvalProposal.input.description && (
                  <div className="text-[11px] text-[var(--exec-text-muted)] font-sans">
                    {runResult.approvalProposal.input.description}
                  </div>
                )}
              </div>

              <div className="flex items-center justify-end gap-2 pt-1">
                <Button
                  variant="secondary"
                  size="sm"
                  onClick={() => handleApproveTask('REJECTED')}
                  disabled={approvalStatus === 'APPROVING'}
                  className="text-xs font-sans"
                >
                  Not Now
                </Button>
                <Button
                  variant="primary"
                  size="sm"
                  onClick={() => handleApproveTask('APPROVED')}
                  disabled={approvalStatus === 'APPROVING'}
                  className="text-xs font-sans bg-emerald-600 hover:bg-emerald-700 text-white font-medium"
                >
                  <Check className="w-3.5 h-3.5 mr-1" />
                  {approvalStatus === 'APPROVING' ? 'Adding...' : 'Approve & Add to Tasks'}
                </Button>
              </div>
            </div>
          )}

          {/* Task Added Notice */}
          {approvalStatus === 'APPROVED' && createdTaskInfo && (
            <div className="p-3.5 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-xs flex items-center justify-between text-emerald-700 dark:text-emerald-400">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                <span>
                  Milestone <strong>&ldquo;{createdTaskInfo.title}&rdquo;</strong> added to your task tracker!
                </span>
              </div>
              <Link href="/tasks" className="underline font-sans text-xs hover:text-emerald-800 font-medium">
                View in Tasks &rarr;
              </Link>
            </div>
          )}

          {/* 6. Collapsible Technical Details (6A–6G Telemetry) */}
          <div className="pt-4 border-t border-[var(--exec-border)]">
            <button
              type="button"
              onClick={() => setShowTechnicalDetails(!showTechnicalDetails)}
              className="flex items-center justify-between w-full py-2 text-xs font-mono text-[var(--exec-text-muted)] hover:text-[var(--exec-text)] transition-colors cursor-pointer"
            >
              <span className="flex items-center gap-2 font-semibold uppercase tracking-wider">
                <Layers className="w-3.5 h-3.5 text-sky-500" />
                View Technical Architecture & Diagnostics (6A–6G Telemetry)
              </span>
              {showTechnicalDetails ? (
                <ChevronUp className="w-4 h-4" />
              ) : (
                <ChevronDown className="w-4 h-4" />
              )}
            </button>

            {showTechnicalDetails && (
              <div className="mt-3 p-4 rounded-xl bg-[var(--exec-surface-secondary)] border border-[var(--exec-border)] space-y-3 text-xs font-mono">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-2 text-[11px]">
                  <div className="p-2.5 rounded-lg bg-[var(--exec-surface)] border border-[var(--exec-border)]">
                    <span className="text-[10px] text-[var(--exec-text-muted)] block uppercase">Phase 6A Intake</span>
                    <span className="font-bold text-[var(--exec-text)]">{runResult.goalUnderstanding?.category || 'GENERAL'}</span>
                    <div className="text-[10px] text-[var(--exec-text-muted)] mt-1">Confidence: {runResult.goalUnderstanding?.confidence}</div>
                  </div>

                  <div className="p-2.5 rounded-lg bg-[var(--exec-surface)] border border-[var(--exec-border)]">
                    <span className="text-[10px] text-[var(--exec-text-muted)] block uppercase">Phase 6C Action Selection</span>
                    <span className="font-bold text-indigo-600 dark:text-indigo-400">{runResult.learningDecision?.decisionType || 'PRACTICE'}</span>
                    <div className="text-[10px] text-[var(--exec-text-muted)] mt-1">Confidence: {runResult.learningDecision?.confidence}</div>
                  </div>

                  <div className="p-2.5 rounded-lg bg-[var(--exec-surface)] border border-[var(--exec-border)]">
                    <span className="text-[10px] text-[var(--exec-text-muted)] block uppercase">Phase 6G Adaptation Policy</span>
                    <span className="font-bold text-emerald-600 dark:text-emerald-400">
                      {runResult.adaptivePolicy?.adaptationSignals[0]?.type || 'PRESERVE_PATTERN'}
                    </span>
                    <div className="text-[10px] text-[var(--exec-text-muted)] mt-1">
                      Signals: {runResult.adaptivePolicy?.adaptationSignals.length || 0}
                    </div>
                  </div>
                </div>

                <div className="p-2.5 rounded-lg bg-[var(--exec-surface)] border border-[var(--exec-border)] text-[10px] text-[var(--exec-text-muted)] space-y-1">
                  <div>Orchestrator Run ID: {runResult.runId}</div>
                  <div>Terminal State: {runResult.status}</div>
                  <div>Write Safety: Phase 5 Human Approval Gate Verified</div>
                  <div>Ground Truth: Phase 1 Corroborated Evidence Authority</div>
                </div>
              </div>
            )}
          </div>

        </div>
      )}
    </div>
  );
}
